sudo: required

services:
  - docker

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/massivedeeps-minecraft
  - export TAG=$TRAVIS_BUILD_NUMBER
  - docker build -t $REPO:$TAG .
  - docker tag $REPO:$TAG $REPO:latest
  - docker push $REPO